#!/usr/bin/env sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
server_dir=$(CDPATH= cd -- "${script_dir}/.." && pwd)
kit_dir=$(CDPATH= cd -- "${server_dir}/../../../../kit" && pwd)

cc_bin=${CC:-gcc}
ld_bin=${LD:-ld}

obj_dir="${server_dir}/build/sample/obj"
pkg_dir="${server_dir}/packages/hello"
out_elf="${pkg_dir}/hello.elf"

cflags="-std=c11 -ffreestanding -fno-stack-protector -fno-builtin -ffunction-sections -fdata-sections -Wall -Wextra -Werror -m64 -mno-red-zone -fno-pic -fno-pie -I${kit_dir}/include"

mkdir -p "${obj_dir}/runtime" "${obj_dir}/sample" "${pkg_dir}"

compile() {
    src=$1
    obj=$2
    "${cc_bin}" ${cflags} -c "${src}" -o "${obj}"
}

compile "${kit_dir}/runtime/runtime.c" "${obj_dir}/runtime/runtime.o"
compile "${kit_dir}/runtime/syscall.c" "${obj_dir}/runtime/syscall.o"
compile "${kit_dir}/runtime/stdio.c" "${obj_dir}/runtime/stdio.o"
compile "${kit_dir}/runtime/libc_string.c" "${obj_dir}/runtime/libc_string.o"
compile "${kit_dir}/runtime/libc_strings.c" "${obj_dir}/runtime/libc_strings.o"
compile "${kit_dir}/runtime/libc_stdlib.c" "${obj_dir}/runtime/libc_stdlib.o"
compile "${kit_dir}/runtime/libc_ctype.c" "${obj_dir}/runtime/libc_ctype.o"
compile "${kit_dir}/runtime/dlfcn.c" "${obj_dir}/runtime/dlfcn.o"
compile "${kit_dir}/runtime/main_adapter.c" "${obj_dir}/runtime/main_adapter.o"
compile "${server_dir}/sample/apps/hello/main.c" "${obj_dir}/sample/hello.o"

"${ld_bin}" -nostdlib -z max-page-size=0x1000 --gc-sections \
    -T "${kit_dir}/linker/user.ld" \
    -o "${out_elf}" \
    "${obj_dir}/runtime/runtime.o" \
    "${obj_dir}/runtime/syscall.o" \
    "${obj_dir}/runtime/stdio.o" \
    "${obj_dir}/runtime/libc_string.o" \
    "${obj_dir}/runtime/libc_strings.o" \
    "${obj_dir}/runtime/libc_stdlib.o" \
    "${obj_dir}/runtime/libc_ctype.o" \
    "${obj_dir}/runtime/dlfcn.o" \
    "${obj_dir}/runtime/main_adapter.o" \
    "${obj_dir}/sample/hello.o"

cat > "${pkg_dir}/package.ini" <<'EOF'
version=1.0.0
target=/shell/hello.elf
description=Hello world package generated by bdt sample.
EOF

printf 'sample package generated: %s\n' "${out_elf}"
